name: http_client
description: Http client proxy package. Under the hood used Dio package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  meta: ^1.3.0
#  flavor_config:
#    path: ../flavor_config

dev_dependencies:
  flutter_lints: ^1.0.0
